#!/usr/bin/env tsx
/**
 * Fetches models from the Ollama Cloud API and writes them to
 * models.generated.ts. Run manually and commit the output when
 * the model catalog changes.
 *
 * Usage:
 *   npx tsx scripts/generate-models.ts
 */

import { writeFileSync } from "node:fs";
import { assembleModels, refreshOllamaCloudModels } from "../models.ts";

console.log("Fetching Ollama Cloud models...");
const raw = await refreshOllamaCloudModels({
  notify: (msg) => console.log(`  ${msg}`),
  onProgress: (p) => {
    if (p.stage === "details" && p.total) {
      process.stdout.write(`\r  ${p.current}/${p.total} models fetched...`);
    }
  },
});

const models = assembleModels(raw);
console.log(`\nAssembled ${models.length} tool-capable models.`);

const out = [
  "// Auto-generated by scripts/generate-models.ts",
  "// Do not edit manually.",
  `// Generated: ${new Date().toISOString()}`,
  `// Model count: ${models.length}`,
  "",
  'import type { ProviderModelConfig } from "@earendil-works/pi-coding-agent";',
  "",
  "export const GENERATED_MODELS: ProviderModelConfig[] = ",
  `${JSON.stringify(models, null, 2)};`,
  "",
].join("\n");

writeFileSync("models.generated.ts", out);
console.log(`Wrote models.generated.ts (${models.length} models).`);
